Page({
    data:{
        title:'按钮操作 Normal',
        subtitle:'',
        disabled:false,
        dataName:'1',
        type:'',
        shape:'default',
        capsuleSize:'medium',
        capsuleMinWidth:false,
        showLoading:false,
        types:[
            {
                name:'default',
                value:'default',
                checked:true
            },
            {
                name:'primary',
                value:'primary'
            },
            {
                name:'ghost',
                value:'ghost'
            },
            {
                name:'text',
                value:'text'
            },
            {
                name:'warn',
                value:'warn'
            },
            {
                name:'warn-ghost',
                value:'warn-ghost'
            },
            {
                name:'light',
                value:'light'
            }
        ],
        shapes:[
            {
                name:'default',
                value:'default',
                checked:true
            },
            {
                name:'capsule',
                value:'capsule'
            }
        ],
        capsuleSizes:[
            {
                name:'small',
                value:'small'
            },
            {
                name:'medium',
                value:'medium',
                checked:true
            },
            {
                name:'large',
                value:'large'
            }
        ]
    },
    onLoad:function(){
    },
    typeChange:function(e){
        this.setData({
            type:e.detail.value
        });
    },
    shapeChange:function(e){
        this.setData({
            shape:e.detail.value
        });
    },
    sizeChange:function(e){
        this.setData({
            capsuleSize:e.detail.value
        });
    },
    titleChange:function(e){
        this.setData({
            title:e.detail.value
        });
    },
    subtitleChange:function(e){
        this.setData({
            subtitle:e.detail.value
        });
    },
    onDisableChange:function(e){
        this.setData({
            disabled:e.detail.value
        });
    },
    onMinWidthChange:function(e){
        this.setData({
            capsuleMinWidth:e.detail.value
        });
    },
    onTest:function(){
    },
    onLoadingChange:function(e){
        this.setData({
            showLoading:e.detail.value
        });
    }
});
