Page({
    download:function(){
        my.downloadFile({
            url:'http://img.alicdn.com/tfs/TB1x669SXXXXXbdaFXXXXXXXXXX-520-280.jpg',
            success:function({apFilePath}){
                my.previewImage({
                    urls:[
                        apFilePath
                    ]
                });
            },
            fail:function(res){
                my.alert({
                    content:res.errorMessage || res.error
                });
            }
        });
    }
});
