Page({
    data:{
        text:'3.1415926',
        copy:''
    },
    handleInput:function(e){
        this.setData({
            text:e.detail.value
        });
    },
    handleCopy:function(){
        my.setClipboard({
            text:this.data.text
        });
    },
    handlePaste:function(){
        my.getClipboard({
            success:({text})=>{this.setData({
                copy:text
            })}
        });
    }
});
