Page({
    data:{
        longPassword:''
    },
    onInput:function(e){
        this.setData({
            longPassword:e.detail.value
        });
    },
    onClear:function(){
        this.setData({
            longPassword:''
        });
    }
});
