Page({
    data:{
        background:[
            'blue',
            'red',
            'yellow'
        ],
        indicatorDots:true,
        autoplay:false,
        vertical:false,
        interval:1000,
        circular:false
    },
    onLoad:function(){
    },
    changeIndicatorDots:function(e){
        this.setData({
            indicatorDots:!this.data.indicatorDots
        });
    },
    changeVertical:function(){
        this.setData({
            vertical:!this.data.vertical
        });
    },
    changeCircular:function(e){
        this.setData({
            circular:!this.data.circular
        });
    },
    changeAutoplay:function(e){
        this.setData({
            autoplay:!this.data.autoplay
        });
    },
    intervalChange:function(e){
        this.setData({
            interval:e.detail.value
        });
    }
});
